# Generated by Django 5.0 on 2023-12-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
