# Generated by Django 5.0 on 2023-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
