# Generated by Django 5.0 on 2023-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
